# Generated by Django 5.0.1 on 2024-02-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleets',
            name='mobile_no',
        ),
    ]
