# Generated by Django 5.0.1 on 2024-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_fleets_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleets',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
