# Generated by Django 5.0.1 on 2024-02-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_fleets_mobile_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleets',
            options={'verbose_name_plural': 'Fleet'},
        ),
    ]
